#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n%2!=0 :
        print("Weird")
    else:
        if n in (2,3,4,5):
            print("Not Weird")
        if n>=6 and n<=20 :
            print("Weird")
        if n>20 :
            print("Not Weird")
# if you have any query contact : nilayp799@gmail.com
