#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())
    n="Not Weird"
    if n%2==1:
        print("Weird")
    elif n>20:
        print("Not Weird")
    elif n>=6:
        print("Weird")
    else:
        print("Not Weird")
# if you have any query contact : nilayp799@gmail.com
