#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))
    arr = arr[::-1]
    print(*arr)

# if you have any query please contact : nilayp799@gmail.com
