#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    n = bin(n)
    n = n[2:]
    r = map(len,n.split('0'))
    print(max(r))

# if you have any query contact : nilayp799@gmail.com
